sylius_grid:
    templates:
        action:
            apply_transition: 'admin/grid/action/apply_transition.html.twig'
        bulk_action:
            apply_transition: 'admin/grid/bulk_action/apply_transition.html.twig'
