# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    locale: 'en'

services:
    _instanceof:
        Sylius\Component\Resource\Repository\RepositoryInterface:
            tags: ['sylius.repository']
        Sylius\Component\Grid\Data\DataProviderInterface:
            tags: ['sylius.grid_data_provider']

    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        bind:
            $dataDir: '%kernel.project_dir%/config/data'

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    app.repository.book:
        class: App\Repository\BookRepository

    App\Menu\AdminMenuBuilder:
        decorates: 'Monofony\SyliusAdminUi\Menu\MenuBuilderInterface'

    App\Shared\Infrastructure\Sylius\Grid\Data\Provider:
        decorates: 'sylius.grid.data_provider'
        arguments:
            $locator: !tagged_locator { tag: 'sylius.grid_data_provider' }
            $decorated: '@.inner'

    sylius.grid.array_to_definition_converter: '@App\Shared\Infrastructure\Sylius\Grid\Definition\ArrayToDefinitionConverter'
    Sylius\Component\Grid\Data\DataProviderInterface: '@sylius.grid.data_provider'
    Sylius\Component\Grid\Provider\GridProviderInterface: '@sylius.grid.chain_provider'
